# Generated by Django 4.2.25 on 2025-10-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_product_image_product_is_creative_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_popolar',
            new_name='is_popular',
        ),
    ]
