# Generated by Django 4.2.25 on 2025-10-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
